services:
  dashboard:
    image: dashboard-eba:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ebanet
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ebadashboard.rule=Host(`app-metricas.agenteeba.online`)"
        - "traefik.http.routers.ebadashboard.entrypoints=websecure"
        - "traefik.http.routers.ebadashboard.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.ebadashboard.loadbalancer.server.port=80"

networks:
  ebanet:
    external: true